In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Week 2 enviroment ready")

Week 2 enviroment ready

In [ ]:
data = {
    "Month": pd.date_range(start="2023-01-01", periods=12, freq="M"),
    "Oil_Rate_bopd": [1600, 1550, 1500, 1420, 1350, 1280, 1200, 1140, 1080, 1020, 970, 920],
    "Gas_Rate_mscfd": [950, 940, 920, 900, 880, 860, 840, 820, 800, 780, 760, 740],
    "Water_Cut": [0.18, 0.20, 0.22, 0.25, 0.28, 0.30, 0.34, 0.38, 0.42, 0.46, 0.50, 0.55]
}

df = pd.DataFrame(data)
df

/tmp/ipython-input-3877064108.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  "Month": pd.date_range(start="2023-01-01", periods=12, freq="M"),

        Month  Oil_Rate_bopd  Gas_Rate_mscfd  Water_Cut
0  2023-01-31           1600             950       0.18
1  2023-02-28           1550             940       0.20
2  2023-03-31           1500             920       0.22
3  2023-04-30           1420             900       0.25
4  2023-05-31           1350             880       0.28
5  2023-06-30           1280             860       0.30
6  2023-07-31           1200             840       0.34
7  2023-08-31           1140             820       0.38
8  2023-09-30           1080             800       0.42
9  2023-10-31           1020             780       0.46
10 2023-11-30            970             760       0.50
11 2023-12-31            920             740       0.55

In [ ]:
df.head()

       Month  Oil_Rate_bopd  Gas_Rate_mscfd  Water_Cut
0 2023-01-31           1600             950       0.18
1 2023-02-28           1550             940       0.20
2 2023-03-31           1500             920       0.22
3 2023-04-30           1420             900       0.25
4 2023-05-31           1350             880       0.28

In [ ]:
df.describe()

                     Month  Oil_Rate_bopd  Gas_Rate_mscfd  Water_Cut
count                   12      12.000000       12.000000  12.000000
mean   2023-07-15 22:00:00    1252.500000      849.166667   0.340000
min    2023-01-31 00:00:00     920.000000      740.000000   0.180000
25%    2023-04-22 12:00:00    1065.000000      795.000000   0.242500
50%    2023-07-15 12:00:00    1240.000000      850.000000   0.320000
75%    2023-10-07 18:00:00    1440.000000      905.000000   0.430000
max    2023-12-31 00:00:00    1600.000000      950.000000   0.550000
std                    NaN     233.242948       70.769579   0.122474

In [ ]:
df["Oil_Produced_bbl"] = df["Oil_Rate_bopd"] * 30
df["Gas_Produced_mscf"] = df["Gas_Rate_mscfd"] * 30

df.head()

,Month,Oil_Rate_bopd,Gas_Rate_mscfd,Water_Cut,Oil_Produced_bbl,Gas_Produced_mscf
0,2023-01-31,1600,950,0.18,48000,28500
1,2023-02-28,1550,940,0.20,46500,28200
2,2023-03-31,1500,920,0.22,45000,27600
3,2023-04-30,1420,900,0.25,42600,27000
4,2023-05-31,1350,880,0.28,40500,26400

In [ ]:
df["Cumulative_Oil_bbl"] = df["Oil_Produced_bbl"].cumsum()
df["Cumulative_Gas_mscf"] = df["Gas_Produced_mscf"].cumsum()

df.tail()

,Month,Oil_Rate_bopd,Gas_Rate_mscfd,Water_Cut,Oil_Produced_bbl,Gas_Produced_mscf,Cumulative_Oil_bbl,Cumulative_Gas_mscf
7,2023-08-31,1140,820,0.38,34200,24600,331200,213300
8,2023-09-30,1080,800,0.42,32400,24000,363600,237300
9,2023-10-31,1020,780,0.46,30600,23400,394200,260700
10,2023-11-30,970,760,0.50,29100,22800,423300,283500
11,2023-12-31,920,740,0.55,27600,22200,450900,305700

In [ ]:
df["GOR_scf_bbl"] = (df["Gas_Rate_mscfd"] * 1000) / df["Oil_Rate_bopd"]
df["Water_Cut_percent"] = df["Water_Cut"] * 100

df.head()

,Month,Oil_Rate_bopd,Gas_Rate_mscfd,Water_Cut,Oil_Produced_bbl,Gas_Produced_mscf,Cumulative_Oil_bbl,Cumulative_Gas_mscf,GOR_scf_bbl,Water_Cut_percent
0,2023-01-31,1600,950,0.18,48000,28500,48000,28500,593.750000,18.0
1,2023-02-28,1550,940,0.20,46500,28200,94500,56700,606.451613,20.0
2,2023-03-31,1500,920,0.22,45000,27600,139500,84300,613.333333,22.0
3,2023-04-30,1420,900,0.25,42600,27000,182100,111300,633.802817,25.0
4,2023-05-31,1350,880,0.28,40500,26400,222600,137700,651.851852,28.0

In [ ]:
df["Operational_Flag"] = np.where(df["Water_Cut"] > 0.45, "High Water Cut", "Normal")

df[["Month", "Water_Cut", "Operational_Flag"]]

        Month  Water_Cut Operational_Flag
0  2023-01-31       0.18           Normal
1  2023-02-28       0.20           Normal
2  2023-03-31       0.22           Normal
3  2023-04-30       0.25           Normal
4  2023-05-31       0.28           Normal
5  2023-06-30       0.30           Normal
6  2023-07-31       0.34           Normal
7  2023-08-31       0.38           Normal
8  2023-09-30       0.42           Normal
9  2023-10-31       0.46   High Water Cut
10 2023-11-30       0.50   High Water Cut
11 2023-12-31       0.55   High Water Cut

In [ ]:
df.to_csv("well_production_cleaned.csv", index=False)

print("File saved: well_production_cleaned.csv")

File saved: well_production_cleaned.csv